---
title: "ENMA 2023 Salud"
output: html_document
date: "2023-12-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(eph)
library(dplyr)
library(readr)

```

## Capitulo de salud - ENMA 2023


Creemos un marckdown por capitulo donde se incluya:
- procesamientos o construccion de variables
- exportacion de datos para excel/csv para los equipos 
- tablas con los datos

```{r carga_datos}

#Cargo los datos ENMA
enma <-  read_csv2("datos\\ENMA_v1.csv",col_names = TRUE,col_types = NULL)
```

##	¿Cuál es su principal cobertura de salud? (q36_salud)

### Analisis univariado



```{r pressure}
##cruce univariado
consulta <- enma %>% 
  group_by(q36_salud) %>% 
  summarise (n = sum(weightvec)) %>%
  mutate(freq = n / sum(n) *100)
consulta
#exporto el csv
write.csv2(consulta,"tables/q36_salud_univ.csv", row.names = FALSE)

```

### Cobertura de salud según género

```{r}

saludxgenero=calculate_tabulates(base = enma, x = 'q36_salud', y = 'genero_var', add.percentage ='col', add.totals = 'row',weights = 'weightvec')
saludxgenero



```

