---
title: "Procesamiento_pedidos"
output: html_document
date: "`r Sys.Date()`"
---


## PEDIDO PROCESAMIENTO VARIOS


```{r setup, message=FALSE, warning=FALSE}

#INSTALO LIBRERIAS QUE VOY A USAR

library(userfriendlyscience)
library(readxl)
library(dplyr)
library(knitr)
library(eph)
library(openxlsx)
library(xlsx)


```


Leo base de datos con nuevas variables:


```{r carga_datos, echo=TRUE, message=FALSE, warning=FALSE}

# Lectura de archivo CSV


enma <-  read_csv("datos/enma_v2.csv",col_names = TRUE,col_types = NULL)


```

```{r exploración, include=FALSE, echo=FALSE}
names(enma)
str(enma)

```

##PEDIDOS ESPECIALES PARTICIPACIÓN

###Pedido3: Participación elecciones locales según región (CABA + GBA)
```{r p3, message=FALSE, warning=FALSE}

pedido3<-calculate_tabulates(base=enma,
                            x="region_CABA_var",
                            y="q68_participacion_elecciones_locales",
                            add.percentage = 'col',
                            add.totals = 'row',
                            weights = "weightvec")



pedido3_tot<-calculate_tabulates(base=enma,
                            x="region_CABA_var",
                            y="q68_participacion_elecciones_locales",
                            add.totals = 'row',
                            weights = "weightvec")


write.xlsx2(as.data.frame(pedido3), "tables/8.Participación/cuadros_participacion.xlsx", row.names = FALSE, sheetName ="pedido41",append = TRUE)


write.xlsx2(as.data.frame(pedido3_tot), "tables/8.Participación/cuadros_participacion.xlsx", row.names = FALSE, sheetName ="pedido41_tot",append = TRUE)

```





