---
title: "Pedidos grales"
output: html_document
date: "`r Sys.Date()`"
---


## PEDIDO PROCESAMIENTO DIMENSIÓN EDUCACIÓN


```{r setup, message=FALSE, warning=FALSE}

#INSTALO LIBRERIAS QUE VOY A USAR

library(userfriendlyscience)
library(readxl)
library(dplyr)
library(tidyverse)
library(knitr)
library(eph)
library(openxlsx)
library(xlsx)


```


Leo base de datos con nuevas variables:


```{r carga_datos, echo=TRUE, message=FALSE, warning=FALSE}

# Lectura de archivo CSV


enma <-  read_csv("datos/ENMA_v2.csv",col_names = TRUE,col_types = NULL)


```

```{r exploración, include=FALSE, echo=FALSE}
names(enma)
str(enma)

```

##PEDIDOS ESPECIALES 

###Pedido59: ESTRATEGIAS PARA CUBRIR GASTOS
```{r q59, warning=FALSE, message=FALSE}


#análisis exploratorio de respuesta múltiple

pedido59_explor<-multiResponse(enma, items = c("Ahorro", "Prestamo_entorno", "Ayuda_estatal", "Ayuda_organizaciones",
                                   "Cuotas", "Fiado", "Prestamo_banco", "Venta_pertenencias", "Ninguna",
                                   "Prefiero_no_reponder"),
                   endorsedOption = 1)


#guardo tabulado
write.xlsx2(as.data.frame(pedido59_explor), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="exploratorio",append = TRUE)



#Resultados
pedido59 <- enma %>%
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="univariado_agrup",append = TRUE)



#Resultados género
pedido59_genero <- enma %>% 
  group_by(genero_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_genero), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="genero",append = TRUE)


#Resultados edad
pedido59_edad <- enma %>% 
  group_by(edad_ag_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_edad), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="edad",append = TRUE)

#Resultados edad cada 10
pedido59_edad10 <- enma %>% 
  group_by(edad_10_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_edad10), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="edad_10",append = TRUE)

#Resultados edad agrupamiento enma 2020
pedido59_edadv2 <- enma %>% 
  group_by(edad_ag2_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_edadv2), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="edadv2",append = TRUE)


#Resultados tiempo de residencia
pedido59_tiempores <- enma %>% 
  group_by(tiempo_residencia_3_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_tiempores), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="tiempo_res",append = TRUE)


#Resultados tiempo de residencia v2
pedido59_tiempores2 <- enma %>% 
  group_by(tiempo_residencia_5_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_tiempores2), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="tiempo_res2",append = TRUE)

#Resultados migración reciente
pedido59_migrec <- enma %>% 
  group_by(migracion_reciente_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_migrec), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="migracion_rec",append = TRUE)

#Resultados nivel educativo
pedido59_niveled <- enma %>% 
  group_by(nivel_educativo_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_niveled), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="nivel_ed",append = TRUE)

#Resultados secundaria completa
pedido59_seccomp <- enma %>% 
  group_by(secundario_completo_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_seccomp), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="sec_comp", append = TRUE)


#Resultados region

pedido59_region <- enma %>% 
  group_by(region_CABA_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_region), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="region",append = TRUE)


#Resultados nacionalidad MERCOSUR
pedido59_MERCOSUR <- enma %>% 
  group_by(nac_agrupada) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_MERCOSUR), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="MERCOSUR",append = TRUE)


#Resultados nacionalidad
pedido59_nacionalidad <- enma %>% 
  group_by(nacionalidad_var) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_nacionalidad), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="nacionalidad",append = TRUE)

#Resultados tenencia DNI
pedido59_dni <- enma %>% 
  group_by(q17_dni_tenencia) %>% 
  summarise(Poblacion= sum(weightvec),
            Descapitalizacion  = sum(weightvec[Descapitalizacion==1]),
            Endeudamiento_informal = sum(weightvec[Endeudamiento_informal == 1]),
            Endeudamiento_formal = sum(weightvec[Endeudamiento_formal == 1]),
            Ayudas         = sum(weightvec[Ayudas == 1]),
            No_responde = sum(weightvec[Prefiero_no_responder == 1]),
            Ninguna = sum(weightvec[Ninguna_anteriores == 1]),
      'Prevalencia Descapitalización'  = round(Descapitalizacion/Poblacion*100,1),
      'Prevalencia Edeudamiento informal'          = round(Endeudamiento_informal/Poblacion*100,1),
'Prevalencia Edeudamiento formal'          = round(Endeudamiento_formal/Poblacion*100,1),
      'Prevalencia Ayudas'            = round(Ayudas/Poblacion*100,1),
'Prevalencia Prefiere no responder'          = round(No_responde/Poblacion*100,1),
      'Prevalencia Ninguna de las anteriores'            = round(Ninguna/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido59_dni), "tables/5.Socioeconómica/cuadros_pedido59.xlsx", row.names = FALSE, sheetName ="dni",append = TRUE)


```




```{r}

#análisis exploratorio de respuesta múltiple

pedido60_explor<-multiResponse(enma, items = c("q60_subsidios_no", "q60_subsidios_auh", "q60_subsidios_embarazo", "q60_subsidios_jubilacion", "q60_subsidios_pension", "q60_subsidios_pension_no_contrib", "q60_subsidios_progresar", "q60_subsidios_potenciar_trabajo", "q60_subsidios_inclusion_joven", "q60_subsidios_tarjeta_alimentar", "q60_subsidios_pieza", "q60_subsidios_desempleo", "q60_subsidios_otro", "q60_subsidios_prefiero_no"),
                   endorsedOption = 1)


#guardo tabulado
write.xlsx2(as.data.frame(pedido60_explor), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="exploratorio",append = TRUE)



#Resultados univariado
pedido60 <- enma %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="univariado",append = TRUE)

#Resultados genero
pedido60_genero <- enma %>% 
  group_by(genero_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_genero), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="genero",append = TRUE)

#Resultados edad
pedido60_edad <- enma %>% 
  group_by(edad_ag_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_edad), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="edad",append = TRUE)

#Resultados edad 10 años
pedido60_edad10 <- enma %>% 
  group_by(edad_10_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_edad10), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="edad_10",append = TRUE)

#Resultados edad2
pedido60_edad2 <- enma %>% 
  group_by(edad_ag2_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_edad2), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="edad2",append = TRUE)

#Resultados tiempo residencia
pedido60_tiempores <- enma %>% 
  group_by(tiempo_residencia_3_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_tiempores), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="tiempo_res",append = TRUE)



#Resultados tiempo residencia2
pedido60_tiempores2 <- enma %>% 
  group_by(tiempo_residencia_5_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_tiempores2), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="tiempo_res2",append = TRUE)


#Resultados migración reciente
pedido60_migrec <- enma %>% 
  group_by(migracion_reciente_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_migrec), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="migracion_rec",append = TRUE)



#Resultados nivel educativo
pedido60_niveled <- enma %>% 
  group_by(nivel_educativo_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_niveled), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="nivel_educativo",append = TRUE)




#Resultados tiempo residencia
pedido60_seccomp <- enma %>% 
  group_by(secundario_completo_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_seccomp), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="secundario_comp",append = TRUE)




#Resultados región
pedido60_region <- enma %>% 
  group_by(region_CABA_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_region), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="region",append = TRUE)



#Resultados MERCOSUR
pedido60_MERCOSUR<- enma %>% 
  group_by(nac_agrupada) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_MERCOSUR), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="MERCOSUR",append = TRUE)



#Resultados NACIONALIDAD
pedido60_nacionalidad<- enma %>% 
  group_by(nacionalidad_var) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_nacionalidad), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="nacionalidad",append = TRUE)



#Resultados dni
pedido60_dni <- enma %>% 
  group_by(q17_dni_tenencia) %>% 
  summarise(Poblacion= sum(weightvec),
            No_recibe  = sum(weightvec[q60_subsidios_no==1]),
            Prestacion_contributiva = sum(weightvec[q60_contributivas == 1]),
            Prestacion_no_contributiva = sum(weightvec[q60_no_contributivas == 1]),
      'No recibe subsidios/prestaciones'  = round(No_recibe/Poblacion*100,1),
      'Recibe prestaciones contributivas'          = round(Prestacion_contributiva/Poblacion*100,1),
'Recibe prestaciones no contributivas'          = round(Prestacion_no_contributiva/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(pedido60_dni), "tables/5.Socioeconómica/cuadros_pedido60.xlsx", row.names = FALSE, sheetName ="dni",append = TRUE)



```

