---
title: "Procesamiento_pedidos"
output: html_document
date: "`r Sys.Date()`"
---


## PEDIDO PROCESAMIENTO VARIOS


```{r setup, message=FALSE, warning=FALSE}

#INSTALO LIBRERIAS QUE VOY A USAR

library(userfriendlyscience)
library(readxl)
library(dplyr)
library(knitr)
library(eph)
library(openxlsx)
library(xlsx)


```


Leo base de datos con nuevas variables:


```{r carga_datos, echo=TRUE, message=FALSE, warning=FALSE}

# Lectura de archivo CSV


enma <-  read_csv("datos/enma_v2.csv",col_names = TRUE,col_types = NULL)


```

```{r exploración, include=FALSE, echo=FALSE}
names(enma)
str(enma)

```

##PEDIDOS ESPECIALES DOCUMENTACIÓN

```{r}

pedido20<-enma %>% 
  group_by(nac_agrupada,q17_dni_tenencia, tiempo_residencia_3_var) %>% 
  summarise(n=sum(weightvec)) %>%  pivot_wider(names_from = nac_agrupada, values_from = n)

enma<-enma %>% 
  mutate(p20=case_when(
    tiempo_residencia_3_var=="0 Hasta 5 años" & nac_agrupada=="MERCOSUR" ~ "MERCOSUR / 0-5 años",
    tiempo_residencia_3_var=="1 Entre 5 y 9 años" & nac_agrupada=="MERCOSUR" ~ "MERCOSUR / 5-9 años",
    tiempo_residencia_3_var=="2 Más de 10 años" & nac_agrupada== "MERCOSUR" ~ "MERCOSUR / 10+ años",
    tiempo_residencia_3_var=="0 Hasta 5 años" & nac_agrupada=="Extra MERCOSUR europeos" ~ "Extra MERCOSUR europeos / 0-5 años",
    tiempo_residencia_3_var=="1 Entre 5 y 9 años" & nac_agrupada=="Extra MERCOSUR europeos" ~ "Extra MERCOSUR europeos / 5-9 años",
    tiempo_residencia_3_var=="2 Más de 10 años" & nac_agrupada== "Extra MERCOSUR europeos" ~ "Extra MERCOSUR europeos / 10+ años",
   tiempo_residencia_3_var=="0 Hasta 5 años" & nac_agrupada=="Extra MERCOSUR no europeos" ~ "Extra MERCOSUR no europeos / 0-5 años",
    tiempo_residencia_3_var=="1 Entre 5 y 9 años" & nac_agrupada=="Extra MERCOSUR no europeos" ~ "Extra MERCOSUR no europeos / 5-9 años",
    tiempo_residencia_3_var=="2 Más de 10 años" & nac_agrupada== "Extra MERCOSUR no europeos" ~ "Extra MERCOSUR no europeos / 10+ años",
   TRUE ~ "NA"))
  

pedido20_f<-calculate_tabulates(base=enma,
                            x="q17_dni_tenencia",
                            y="p20",
                            add.percentage = 'col',
                            add.totals = 'row',
                            weights = "weightvec")

                            
pedido21<-enma %>% 
  group_by(nacionalidad_var,q17_dni_tenencia, tiempo_residencia_3_var) %>%   summarise(n=sum(weightvec)) %>%  pivot_wider(names_from = nacionalidad_var, values_from = n)



write.xlsx2(as.data.frame(pedido20_f), "tables/2.Documentación/cuadros_documentación.xlsx", row.names = FALSE, sheetName ="pedido20b",append = TRUE)


write.xlsx2(as.data.frame(pedido21), "tables/2.Documentación/cuadros_documentación.xlsx", row.names = FALSE, sheetName ="pedido21",append = TRUE)


unique(enma$tiempo_residencia_5_var)

```





```{r}
enma<-enma %>% 
  mutate(q33_recod=case_when(
    (q33_incoveniente_educacion_no==1 & (q33_inconveniente_educacion_dni!=1 & q33_incoveniente_educacion_cupo!=1 & q33_inconveniente_educacion_inscripcion!=1   & q33_inconveniente_educacion_documentacion_origen!=1  &
      q33_inconveniente_educacion_documentacion_argentina!=1 &
      q33_inconveniente_educacion_otro!=1)) ~ 1,
    q33_inconveniente_educacion_dni==1 |   q33_incoveniente_educacion_cupo==1 |    q33_inconveniente_educacion_inscripcion==1|    q33_inconveniente_educacion_documentacion_origen==1 |    q33_inconveniente_educacion_documentacion_argentina==1 |    q33_inconveniente_educacion_otro==1 ~2,
    TRUE ~ 0))

q33_ver<-enma %>% 
  group_by(q33_recod) %>%   summarise(n=sum(weightvec))


```

##PEDIDO Q25: NATURALIZACIÓN

¿Sabía usted que, a partir de los dos años de residencia continua en el país, puede naturalizarse y adquirir así la nacionalidad argentina?

```{r}
names(enma)

q25<-enma %>% 
  group_by(q25_naturalizacion) %>%   summarise(n=sum(weightvec))

q25<-calculate_tabulates(base=enma,
                            x="q25_naturalización",
                            add.percentage = 'col',
                            add.totals = 'row',
                            weights = "weightvec")

```


##PEDIDO RECODIFICACIÓN Q21
```{r}


q20_q17<-calculate_tabulates(base=enma,
                             x="q20_dni_dificultad_binaria",
                            y="q17_dni_tenencia",
                               add.totals = 'row',
                               weights = 'weightvec')

#guardo tabulado
write.xlsx2(as.data.frame(q20_q17), "tables/2.Documentación/cuadros_q21.xlsx", row.names = FALSE, sheetName ="q20",append = TRUE)


#Resultados 
q21rec<- enma %>% 
  filter(q20_dni_dificultad_binaria=="Si") %>% 
    summarise(Poblacion= sum(weightvec),
            Burocratico_adm  = sum(weightvec[q21_burocratico_adm==1]),
            Falta_info = sum(weightvec[q21_falta_info == 1]),
            No_cumple_req = sum(weightvec[q21_no_cumple_req == 1]),
            Otros = sum(weightvec[q21_otros == 1]),
      'Burocrático-adm'  = round(Burocratico_adm/Poblacion*100,1),
      'Falta información'          = round(Falta_info/Poblacion*100,1),
'No cumple con requisitos'          = round(No_cumple_req/Poblacion*100,1),
'Otras dificultades' = round(Otros/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(q21rec), "tables/2.Documentación/cuadros_q21.xlsx", row.names = FALSE, sheetName ="q21",append = TRUE)

#Resultados por tenencia dni

q21_dni<- enma %>% 
  group_by(q17_dni_tenencia) %>% 
  filter(q20_dni_dificultad_binaria=="Si") %>% 
  summarise(Poblacion= sum(weightvec),
            Burocratico_adm  = sum(weightvec[q21_burocratico_adm==1]),
            Falta_info = sum(weightvec[q21_falta_info == 1]),
            No_cumple_req = sum(weightvec[q21_no_cumple_req == 1]),
            Otros = sum(weightvec[q21_otros == 1]),
      'Burocrático-adm'  = round(Burocratico_adm/Poblacion*100,1),
      'Falta información'          = round(Falta_info/Poblacion*100,1),
'No cumple con requisitos'          = round(No_cumple_req/Poblacion*100,1),
'Otras dificultades' = round(Otros/Poblacion*100,1))

#guardo tabulado
write.xlsx2(as.data.frame(q21_dni), "tables/2.Documentación/cuadros_q21.xlsx", row.names = FALSE, sheetName ="q21_dni",append = TRUE)

#Resultados según situación documentaria

unique(enma$q17_dni_tenencia)
q21_sitdoc<- enma %>% 
  group_by(q19_situacion_documentaria) %>% 
  summarise(Poblacion= sum(weightvec),
            Burocratico_adm  = sum(weightvec[q21_burocratico_adm==1]),
            Falta_info = sum(weightvec[q21_falta_info == 1]),
            No_cumple_req = sum(weightvec[q21_no_cumple_req == 1]),
            Otros = sum(weightvec[q21_otros == 1]),
      'Burocrático-adm'  = round(Burocratico_adm/Poblacion*100,1),
      'Falta información'          = round(Falta_info/Poblacion*100,1),
'No cumple con requisitos'          = round(No_cumple_req/Poblacion*100,1),
'Otras dificultades' = round(Otros/Poblacion*100,1)) %>% 
  slice(1:8)

temp_qry <- enma %>% 
 group_by(q19_situacion_documentaria, q20_dni_dificultad_binaria) %>%
 summarise(cantidad= round(sum(weightvec),0)) 
temp_qry

#guardo tabulado
write.xlsx2(as.data.frame(q21_sitdoc), "tables/2.Documentación/cuadros_q21.xlsx", row.names = FALSE, sheetName ="q21_sitdoc",append = TRUE)

```

